
spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost/jpa_udemy
    username: postgres
    password: root

  database:
    driverClassName: org.postgresql.Driver # importante

  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: create-drop # importante
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        #        hbm2ddl:
        #          import_files: data.sql
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
server:
  port: 8081